package operaciones;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import main.ClienteGUI;
import main.ClienteSocket;

/**
 *
 * @author Irvin Carapia Hernández
 */
public class EliminarArchivo extends javax.swing.JFrame {

    /**
     * Creates new form ClienteGUI
     */
    public EliminarArchivo(ArrayList<String> archivos) {
        initComponents();
        configuracionVentana();
        instanciarComboBox(archivos);
    }

    private void configuracionVentana() {
        setSize(750, 320);
        setLocationRelativeTo(null);
    }

    private void instanciarComboBox(ArrayList<String> archivos) {
        jComboBoxArchivo.removeAllItems(); // Limpia los elementos existentes en el ComboBox
        for (String archivo : archivos) {
            jComboBoxArchivo.addItem(archivo); // Agrega cada nombre de archivo al ComboBox
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelMenu = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jComboBoxArchivo = new javax.swing.JComboBox<>();
        jButtonAtras = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eliminar Archivo");
        setName("eliminarArchivo"); // NOI18N
        setResizable(false);

        jPanelMenu.setPreferredSize(new java.awt.Dimension(640, 320));
        jPanelMenu.setLayout(new java.awt.GridBagLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTitulo.setText("Seleccione un archivo para eliminarlo: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        jPanelMenu.add(jLabelTitulo, gridBagConstraints);

        jComboBoxArchivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxArchivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxArchivoItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 285;
        gridBagConstraints.ipady = 25;
        jPanelMenu.add(jComboBoxArchivo, gridBagConstraints);

        jButtonAtras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonAtras.setText("Atrás");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weighty = 0.2;
        jPanelMenu.add(jButtonAtras, gridBagConstraints);

        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setEnabled(false);
        jButtonEliminar.setFocusable(false);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        jPanelMenu.add(jButtonEliminar, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        ClienteGUI clienteGUI = new ClienteGUI();

        setVisible(false);
        dispose();

        clienteGUI.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        if (jComboBoxArchivo.getSelectedItem() != null) {
            String nombreArchivo = (String) jComboBoxArchivo.getSelectedItem();
            try {
                // Crear una instancia de ClienteSocket y comunicarse con el servidor
                ClienteSocket clienteSocket = new ClienteSocket("192.168.1.73", 8000);

                // Enviar una solicitud al servidor para realizar la operación de eliminación
                clienteSocket.enviarMensaje("ELIMINAR");
                clienteSocket.enviarMensaje(nombreArchivo);

                JOptionPane.showMessageDialog(this, "El archivo: " + nombreArchivo + " se ha eliminado con éxito");

                clienteSocket.cerrarConexion();
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(LeerArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jComboBoxArchivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxArchivoItemStateChanged
        if (jComboBoxArchivo.getSelectedItem() != null) {
            jButtonEliminar.setEnabled(true);
            jButtonEliminar.setFocusable(true);
        }
    }//GEN-LAST:event_jComboBoxArchivoItemStateChanged

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JComboBox<String> jComboBoxArchivo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
